delamaison/config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :users

  resources :items

  resources :topics

  root 'items#index'

end

delamaison/app/models/item.rb
class Item < ActiveRecord::Base
end

delamaison/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :message
end

delamaison/app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
end

delamaison/app/models/user.rb
class User < ActiveRecord::Base
  has_many  :messages
  has_many  :topics
end

delamaison/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

delamaison/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :image_url, :prix, :description, :style, :img_link, :color, :material)
    end
end

delamaison/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:title, :content, :user_id, :message_id)
    end
end

delamaison/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :content, :user_id)
    end
end

delamaison/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :age, :email, :image_url)
    end
end

delamaison/app/helpers/application_helper.rb
module ApplicationHelper
end

delamaison/app/helpers/items_helper.rb
module ItemsHelper
end

delamaison/app/helpers/messages_helper.rb
module MessagesHelper
end

delamaison/app/helpers/topics_helper.rb
module TopicsHelper
end

delamaison/app/helpers/users_helper.rb
module UsersHelper
end

delamaison/app/views/items/_form.html.haml
= simple_form_for(@item, html: { class: 'form-horizontal' })do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :name
  .field
    = f.input :image_url
  .field
    = f.number_field :prix
  .field
    = f.input :description
  .field
    = f.input :style
  .field
    = f.input :img_link
  .field
    = f.input :color
  .field
    = f.input :material
  .actions
    = f.button :submit

delamaison/app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

delamaison/app/views/items/index.html.haml
.jumbotron
  .jumbotron-title
    %h1
      Inspirations & Solutions Pour La Maison
  .jumbotron-menu
    .je-cherche{style: "background-color: brown;"}
      Je cherche
      .dropdown
        %a.dropdown-toggle#dropdownMenu1{:href => "#", "role" => "button", "data-toggle" => "dropdown", "data-target" => "#", style: "background-color: white;"}
          "......................................."
        %ul.dropdown-menu{"role" => "menu"}
          %li
            %a{:href => "#link1"}
              une idée
            %a{:href => "#link2"}
              une couleur
            %a{:href => "#link3"}
              un luminaire
            %a{:href => "#link4"}
              un meuble
    .pour{style: "background-color: brown;"}
      pour
      .dropdown
        %a.dropdown-toggle#dropdownMenu1{:href => "#", "role" => "button", "data-toggle" => "dropdown", "data-target" => "#", style: "background-color: white;"}
          "......................................."
        %ul.dropdown-menu{"role" => "menu"}
          %li
            %a{:href => "#link1"}
              ma chambre
            %a{:href => "#link2"}
              ma cuisine
            %a{:href => "#link3"}
              ma salle de bain
            %a{:href => "#link4"}
              mon salon
  .subtitle-jumbotron
    .btn
      Découvrir la communauté

delamaison/app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

delamaison/app/views/items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item.name
%p
  %b Image url:
  = @item.image_url
%p
  %b Prix:
  = @item.prix
%p
  %b Description:
  = @item.description
%p
  %b Style:
  = @item.style
%p
  %b Img link:
  = @item.img_link
%p
  %b Color:
  = @item.color
%p
  %b Material:
  = @item.material

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path

delamaison/app/views/layouts/_footer.html.haml
#footer-main
  #footer_zone_rond
  #footer-page
    #footer-page-container
      #footer_zone
        #footer_zone_top
          %span.footer_zone_title Les avis clients
          #footer_zone_top_1.footer_zone_top_element
            Votre satisfaction
            = succeed "est" do
              %br/
          #footer_zone_top_2.footer_zone_top_element
            %a{:href => "http://www.trustpilot.fr/review/www.delamaison.fr", :target => "_blank"}
              .imgReviews
                #imgTrustpilot
              .noteReviews
                .starRateReviews
                  .starReviews.numeroEtoile.numeroEtoile4Gris
                  %span.rateReviews
                    %span{:itemprop => "average"} 7.3
                    \/
                    %span{:itemprop => "best"} 10
              %span.textReviews 11290 évaluations sur Truspilot
          #footer_zone_top_3.footer_zone_top_element
            %a{:href => "http://www.shopzilla.fr/mid--115093/marchand", :target => "_blank"}
              .imgReviews
                #imgShopzilla
              .noteReviews{:itemscope => "", :itemtype => "http://data-vocabulary.org/Review-aggregate"}
                .starRateReviews{:style => "width: 110px;"}
                  .starReviews.numeroEtoile.numeroEtoile4Gris
                    %meta{:content => "0", :itemprop => "rating"}/
                  %span.rateReviews{:itemprop => "rating", :itemscope => "", :itemtype => "http://data-vocabulary.org/Rating"}
                    %span{:itemprop => "average"} 4
                    \/
                    %span{:itemprop => "best"} 5
              %span.textReviews
                %span{:itemprop => "votes"} 9145  évaluations
                %span{:itemprop => "itemreviewed", :style => "display:none;"} Delamaison.fr
                sur Shopzilla
          #footer_zone_top_4.footer_zone_top_element.last-child
            %a{:href => "https://www.ekomi.fr/avis-clients-delamaisonfr.html", :target => "_blank"}
              .imgReviews
                #imgEkomi
              .noteReviews
                .starReviews.starReviewsLast.numeroEtoile.numeroEtoile4Gris
              %span.textReviews évaluations sur Ekomi
        #footer_zone_separator
        #footer_zone_separator_button Voir les évaluations
        #footer_zone_bottom_reviews
          #footer_reviews
            .footer_reviews_element
              .footer_reviews_element_star.numeroEtoile.numeroEtoile5Rose
              .footer_reviews_element_title Parfait, je commanderai à nouveau!
              .footer_reviews_element_desc
                Ayant déjà commandé chez Delamaison.fr, j'ai souhaité acheter un sapin de Noël artificiel.
                %br>/
                L'article a été envoyé rapidement, et dans de bonnes conditions, comme pour ma 1ère commande.
              .footer_reviews_element_pseudo Anais
              .footer_reviews_element_datetime 18-01-2015 23:20
            .footer_reviews_element
              .footer_reviews_element_star.numeroEtoile.numeroEtoile4Rose
              .footer_reviews_element_title Satisfaite
              .footer_reviews_element_desc Livraison dans les délais, Aucun souci.
              .footer_reviews_element_pseudo MATTER67
              .footer_reviews_element_datetime 18-01-2015 22:22
            .footer_reviews_element.last-child
              .footer_reviews_element_star.numeroEtoile.numeroEtoile5Rose
              .footer_reviews_element_title Tres bien
              .footer_reviews_element_desc Livraison tres rapide et parfaitement conforme a la commande
              .footer_reviews_element_pseudo Denis
              .footer_reviews_element_datetime 18-01-2015 22:21
          #footer_reviews_close
        #footer_zone_bottom
          %span.footer_zone_title Suivez notre actualité
          #footer_zone_bottom_2.footer_zone_bottom_element
            #footer_zone_bottom_news_title Inscrivez-vous à nos newsletters
            #footer_zone_bottom_news_desc
              Découvrez tout sur la déco, les tendances et les nouveautés des grandes marques.
              %br/
              Profitez des ventes privées et autres offres exceptionnelles.
            #footer_zone_bottom_news_input
              %form{:action => "create_account.php", :method => "post", :onsubmit => "check_subscribe();return false;"}
                %input{:name => "newsletter_quick_subscribe", :type => "hidden", :value => "true"}/
                %input#footer_zone_bottom_input{:maxlength => "50", :name => "email_address", :placeholder => "Votre adresse e-mail", :type => "text"}/
                %input#footer_zone_bottom_button{:type => "submit", :value => "ENVOYER"}/
          #footer_zone_bottom_3.footer_zone_bottom_element.last-child
            #footer_zone_bottom_news_title Devenez notre meilleur fan
            #footer_zone_bottom_news_logos
              %a{:href => "http://www.facebook.com/delamaison.fr", :target => "_blank"}
                .footer_logo.footer_logo_facebook
              %a{:href => "http://twitter.com/delamaison", :target => "_blank"}
                .footer_logo.footer_logo_twitter
              %a{:href => "http://www.youtube.com/user/delamaisonfr", :target => "_blank"}
                .footer_logo.footer_logo_youtube
              %a{:href => "https://plus.google.com/100723833224758665122", :target => "_blank"}
                .footer_logo.footer_logo_google
              %a{:href => "http://pinterest.com/delamaison/", :target => "_blank"}
                .footer_logo.footer_logo_pinterest
              %a{:href => "http://instagram.com/delamaisonfr", :target => "_blank"}
                .footer_logo.footer_logo_instagram
              %a{:href => "http://blog-deco-delamaison.fr/", :target => "_blank"}
                .footer_logo.footer_logo_blog.last
  #footer-links
    #footer-backlink
      #footer_links
        %a.links_footer{:href => "http://www.delamaison.fr/parrainage.php#"}
        %a.links_footer{:href => "http://www.delamaison.fr/qui_sommes_nous.php#"} Mieux nous connaître
        %span.separateurs_footer  | 
        %a.links_footer{:href => "http://www.delamaison.fr/engagements.php#"} Nos engagements
        %span.separateurs_footer  | 
        %a.links_footer{:href => "/marques.html"} Nos marques
        %span.separateurs_footer  | 
        %a.links_footer{:href => "http://blog-deco-delamaison.fr/", :target => "_blank"} Blog déco
        %span.separateurs_footer  | 
        %a{:href => "customers_comments.php", :title => "témoignages de nos clients"} Avis clients
        %span.separateurs_footer  | 
        %a.links_footer{:href => "http://www.delamaison.fr/faq.php#"} Faq
        %span.separateurs_footer  | 
        %a#popupConseillerSC2.links_footer{:href => "#", :onclick => "return false;", :rel => "nofollow"} Contact
        %span.separateurs_footer  | 
        %a{:href => "application-mobile.html", :title => "Application mobile"} Application mobile
        %div{:style => "height:2px"}
        / <a class="links_footer" href="http://revue-presse.delamaison.fr/" target="_blank">Revue de presse</a>
        /
          <span class=separateurs_footer> | </span>
          <a class=links_footer href="/vente-soldes.html" title="Soldes, Réductions, promos, bon plans">Soldes</a>
          <span class=separateurs_footer> | </span>
        %a.links_footer{:href => "http://www.delamaison.fr/confidentialite.php#"} Mentions legales
        %span.separateurs_footer  | 
        %a.links_footer{:href => "http://www.delamaison.fr/cgv.php#"} CGV
        %span.separateurs_footer  | 
        %a.links_footer{:href => "affiliation_partenariat.php"} Affiliation et partenariats
        %span.separateurs_footer  | 
        %a.links_footer{:href => "contact_us.php"} Contact pro
        %span.separateurs_footer  | 
        %a.links_footer{:href => "contact_press.php"} Contact presse
        %span.separateurs_footer  | 
        %a.links_footer{:href => "/recrutement-delamaison.html#"} Rejoignez-nous
        %span.separateurs_footer  | 
        %a.links_footer{:href => "http://jeu.delamaison.fr/#"} Jeu concours
      #footer_condition_promo
        %a{:href => "#", :onclick => "showLayerOffreSpecial();return false;"}
          * Conditions des offres promotionnelles en cours
        ** Tous les stocks s'entendent dans la limite des stocks disponibles. Promotions : Offres dans la limite des stocks disponibles.
        Les photos des produits ne sont pas contractuelles. Le produit ne comprend
        pas forcément tous les éléments de la photo. Certaines photos sont
        la propriété des fabricants des produits considérés.
        %span#footer_copyright
          copyright © 2000-2015    elbee sas - tous droits réservés
    #footer-paiement
      #footer_logo
        .sprite_footer.spriteFooter1
        %a{:href => "#", :onclick => "OpenPopUpCenter('http://partenaires.cofinoga.fr/delamaison.do',836,744);return false;", :style => "float:left"}
          .sprite_footer.spriteFooter2
        .sprite_footer.spriteFooter3
        %a{:href => "http://www.fevad.com/", :style => "float:left;", :target => "_blank"}
          .sprite_footer.spriteFooter4
        / div class="sprite_footer spriteFooter5"></div
        .spriteFooterSeparator
        .textFooter Delamaison.fr, leader de l'équipement de la maison fait partie du groupe Adeo :
        .sprite_footer.spriteFooter6

delamaison/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Delamaison</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<div>
  <%= render 'layouts/header' %>
</div>
<div class="container">
  <%= yield %>
</div>
    <%= render 'layouts/footer' %>
</body>
</html>

delamaison/app/views/messages/_form.html.haml
= form_for @message do |f|
  - if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :message
    = f.text_field :message
  .actions
    = f.submit 'Save'

delamaison/app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', @message
\|
= link_to 'Back', messages_path

delamaison/app/views/messages/index.html.haml
%h1 Listing messages

%table
  %thead
    %tr
      %th Title
      %th Content
      %th User
      %th Message
      %th
      %th
      %th
      
  %tbody
    - @messages.each do |message|
      %tr
        %td= message.title
        %td= message.content
        %td= message.user
        %td= message.message
        %td= link_to 'Show', message
        %td= link_to 'Edit', edit_message_path(message)
        %td= link_to 'Destroy', message, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Message', new_message_path

delamaison/app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', messages_path

delamaison/app/views/messages/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @message.title
%p
  %b Content:
  = @message.content
%p
  %b User:
  = @message.user
%p
  %b Message:
  = @message.message

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path

delamaison/app/views/topics/_form.html.haml
= simple_form_for @topic do |f|
  - if @topic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
      %ul
        - @topic.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :title
  .field
    = f.input :content
  .field
    = f.input :user
  .field
    = f.input :salon
  .field
    = f.input :interieur
  .field
    = f.input :imprime
  .actions
    = f.button :submit

delamaison/app/views/topics/edit.html.haml
%h1 Editing topic

= render 'form'

= link_to 'Show', @topic
\|
= link_to 'Back', topics_path

delamaison/app/views/topics/index.html.haml
%h1 Listing topics

%table
  %thead
    %tr
      %th Title
      %th Content
      %th User
      %th User
      %th LAURA PIRON
      %th
      %th
      
  %tbody
    - @topics.each do |topic|
      %tr
        %td= topic.title
        %td= topic.content
        %td= topic.user_id
        %td= topic.user
        %td= link_to 'Show', topic
        %td= link_to 'Edit', edit_topic_path(topic)
        %td= link_to 'Destroy', topic, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Topic', new_topic_path

delamaison/app/views/topics/new.html.haml
%h1 New topic

= render 'form'

= link_to 'Back', topics_path

delamaison/app/views/topics/show.html.haml
.topics
  %p#notice= notice

  %p
    %b Title:
    = @topic.title
  %p
    %b Content:
    = @topic.content

  %p
    %b User:
    = @topic.user.name
  .styles
    %b
      Styles
    .styles-btn
      .btn-primary
        = @topic.salon
      .btn-danger
        = @topic.imprime
      .btn-warning
        = @topic.interieur

    - Message.where(topic_id: @topic.id).each do |message|
      .message
        .message-user
          .user-image
            =image_tag(message.user.image_url, size: "150x100")
          .user-name
            = message.user.name
        .message-title
          =message.title
        .message-content
          = message.content
    .message
      .message-user
        .user-image
          =image_tag("https://media.licdn.com/mpr/mpr/shrink_500_500/p/4/005/021/3bd/22b1e6a.jpg", size: "150x100")
        .user-name
          Gaëtan
      .message-title
        Proposition 4
      .message-content
        Hey ! Salut Frank ! regarde cette article :)
        .item-name
          = Item.first.name
        .item-image
          = image_tag Item.first.image_url, size: "150x100"
        .item-price
          = Item.first.prix

= link_to 'Edit', edit_topic_path(@topic)
\|
= link_to 'Back', topics_path

delamaison/app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :age
    = f.number_field :age
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :image_url
    = f.text_field :image_url
  .actions
    = f.submit 'Save'

delamaison/app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

delamaison/app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Age
      %th Email
      %th Image url
      %th
      %th
      %th
      
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.age
        %td= user.email
        %td= user.image_url
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

delamaison/app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

delamaison/app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Age:
  = @user.age
%p
  %b Email:
  = @user.email
%p
  %b Image url:
  = @user.image_url

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path